<?php
/** 
* Magento CZ Module
* 
* NOTICE OF LICENSE 
* 
* This source file is subject to the Open Software License (OSL 3.0) 
* that is bundled with this package in the file LICENSE.txt. 
* It is also available through the world-wide-web at this URL: 
* http://opensource.org/licenses/osl-3.0.php 
* If you did of the license and are unable to 
* obtain it through the world-wide-web, please send an email 
* to magentocz@gmail.com so we can send you a copy immediately. 
* 
* @copyright Copyright (c) 2014 GetReady s.r.o. (https://getready.cz)
* 
*/ 
?>
<?php
$_code		= $this->getMethodCode();
$_extra_fee	= $this->getMethod()->getAddressCosts($this->getShippingAddress());

$_extra_fee_excl = $this->convertPrice(Mage::helper('magentocz_cashondelivery')->getCodPrice($_extra_fee, $this->helper('magentocz_cashondelivery')->displayCodFeeIncludingTax(), $this->getShippingAddress()), true);
$_extra_fee_incl = $this->convertPrice(Mage::helper('magentocz_cashondelivery')->getCodPrice($_extra_fee, true, $this->getShippingAddress()), true);

$_codFeeStr = $_extra_fee_excl;
if ($this->helper('magentocz_cashondelivery')->displayCodBothPrices() && ($_extra_fee_incl != $_extra_fee_excl)) {
	$_codFeeStr .= ' ('.$this->__('Incl. Tax').' '.$_extra_fee_incl.')';
}
?>
<?php if($this->getMethod()->getCustomText() || $_extra_fee || Mage::getStoreConfig('payment/magentocz_cashondelivery/display_zero_fee')): ?>
<fieldset class="form-list">
	<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
        <?php if($_extra_fee || Mage::getStoreConfig('payment/magentocz_cashondelivery/display_zero_fee')): ?>
		<li><?php echo $this->__('You will be charged an extra fee of %s.', $_codFeeStr) ?></li>
        <?php endif; ?>
		<?php if ($this->getMethod()->getCustomText()): ?>
		<li>
			<?php echo $this->getMethod()->getCustomText() ?>
		</li>
		<?php endif; ?>
	</ul>
</fieldset>
<?php endif; ?>